name: CI/CD Pipeline for Staging

on:
  push:
    branches:
      - staging  
jobs:
  validate-and-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-docker-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-docker-

    - name: Docker Compose Up for Validation
      run: |
        docker-compose -f docker-compose.yml up -d
        docker-compose ps  # Verify the containers are up

    - name: Wait for Service Readiness (Health Check)
      run: |
        # Assuming your service is running on port 80
        echo "Waiting for service to be healthy..."
        for i in {1..30}; do
          if curl -s http://localhost:80/health_check_endpoint; then
            echo "Service is healthy"
            break
          fi
          echo "Service not ready, retrying..."
          sleep 5
        done
        if [ $i -eq 30 ]; then
          echo "Service failed to start within the expected time"
          exit 1
        fi

    - name: Docker Compose Down
      run: |
        docker-compose down

    - name: Build Docker Image
      run: |
        docker build -t ClayGrant/codeyou-devops-with-aws-final-project-saleor-full:staging .

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker Image to DockerHub
      run: |
        docker push ClayGrant/codeyou-devops-with-aws-final-project-saleor-full:staging